export const STATIC_ROUTES = [
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-21 17:32:26',
    updateUser: '1',
    updateUserAvatar: 'https://ts1.tc.mm.bing.net/th/id/R-C.6a6d08e2769800fe626bdf3ccbd7b2bf?rik=f2hCf09zz%2f9k3w&riu=http%3a%2f%2fpic.imeitou.com%2fuploads%2fallimg%2f240318%2f10-24031Q62553.jpg&ehk=xiruSwoAcF8DeN%2bzMk5g%2bRv%2baNwdPsxj4YUV4CLEe2A%3d&risl=&pid=ImgRaw&r=0',
    updateUserName: '超级管理员',
    id: '1',
    pid: '0',
    name: 'home',
    path: '/home',
    componentPath: '/home/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '仪表盘',
    icon: 'dashboard',
    sort: 1,
    keepAlive: true,
    visible: true,
    pined: true,
    withoutTab: true,
    parameters: null,
    extraParams: null,
    children: null,
  },
]
